<?php

declare(strict_types=1);

namespace Tests\Feature\Signing;

use App\Exceptions\Signing\ContractSigningException;
use App\Models\AuditEvent;
use App\Models\Contract;
use App\Models\Signature;
use App\Models\StoredFile;
use App\Models\User;
use App\Services\Signing\ContractSigningFailurePresenter;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

/**
 * Route-level M12 signing action against the real endpoint, middleware and the
 * real M11 ContractSigningService (real OpenSSL detached CMS on success).
 */
final class ContractSigningHttpTest extends ContractSigningTestCase
{
    /**
     * @return array{user: User, contract: Contract, finalPdf: StoredFile, token: string}
     */
    private function signableFixture(): array
    {
        $ctx = $this->registerValidSigner();
        $user = $ctx['user'];
        $this->actingAs($user);
        $contract = $this->seedContract($user);
        $finalPdf = $this->attachFinalPdf($contract, $user, $this->pdfBytes('http'));
        $token = $this->activatePublicVerification($contract, $finalPdf);

        return ['user' => $user, 'contract' => $contract, 'finalPdf' => $finalPdf, 'token' => $token];
    }

    private function sign(Contract $contract)
    {
        return $this->post(route('contracts.sign.store', $contract));
    }

    // --- route + authorization ----------------------------------------------

    public function test_route_uses_post_auth_and_throttle_middleware(): void
    {
        $route = Route::getRoutes()->getByName('contracts.sign.store');

        $this->assertNotNull($route);
        $this->assertSame(['POST'], $route->methods());
        $this->assertContains('auth', $route->gatherMiddleware());
        $this->assertContains('throttle:6,1', $route->gatherMiddleware());
        $this->assertContains('web', $route->gatherMiddleware());
    }

    public function test_guest_cannot_sign(): void
    {
        $f = $this->signableFixture();
        auth()->logout();

        $this->sign($f['contract'])->assertRedirect(route('login'));
        $this->assertSame(0, Signature::query()->count());
        $this->assertSame(0, $this->p7sCount());
    }

    public function test_foreign_authenticated_user_cannot_sign(): void
    {
        $f = $this->signableFixture();
        $this->actingAs(User::factory()->create());

        $this->sign($f['contract'])->assertForbidden();
        $this->assertSame(0, Signature::query()->count());
        $this->assertSame(0, $this->p7sCount());
        $this->assertSame(0, AuditEvent::query()->where('action', 'contract.signature_completed')->count());
    }

    public function test_caller_supplied_actor_fields_are_ignored(): void
    {
        $f = $this->signableFixture();
        $other = User::factory()->create();

        // Junk actor identifiers in the payload must never choose the signer.
        $this->post(route('contracts.sign.store', $f['contract']), [
            'actor_user_id' => $other->id,
            'signed_user_id' => $other->id,
            'user_id' => $other->id,
        ])->assertRedirect(route('contracts.index'));

        $signature = Signature::query()->sole();
        $this->assertSame((int) $f['user']->id, (int) $signature->signed_user_id);
        $this->assertNotSame((int) $other->id, (int) $signature->signed_user_id);
    }

    // --- success + idempotency ----------------------------------------------

    public function test_owner_first_submit_creates_exactly_one_cms_and_signature(): void
    {
        $f = $this->signableFixture();

        $this->assertSame(0, DB::transactionLevel(), 'the HTTP layer must not run inside a transaction');

        $response = $this->sign($f['contract']);

        $response->assertRedirect(route('contracts.index'))->assertSessionHas('success');
        $this->assertStringNotContainsString($f['token'], (string) session('success'));

        $signature = Signature::query()->sole();
        $this->assertSame(Signature::STATUS_COMPLETED, $signature->status);
        $this->assertSame((int) $f['user']->id, (int) $signature->signed_user_id);
        $this->assertSame((int) $f['finalPdf']->id, (int) $signature->source_file_id);
        $this->assertSame(1, StoredFile::query()->where('purpose', StoredFile::PURPOSE_CMS_SIGNATURE)->count());
        $this->assertSame(1, $this->p7sCount());
        $this->assertSame(1, AuditEvent::query()->where('action', 'contract.signature_completed')->count());

        // The final PDF was NOT regenerated by signing.
        $fresh = $f['contract']->fresh();
        $this->assertSame((int) $f['finalPdf']->id, (int) $fresh->final_pdf_file_id);
        $this->assertSame(1, $this->finalPdfCount());
    }

    public function test_double_submit_is_idempotent_without_duplicates(): void
    {
        $f = $this->signableFixture();

        $this->sign($f['contract'])->assertSessionHas('success');
        $second = $this->sign($f['contract']);

        $second->assertRedirect(route('contracts.index'))->assertSessionHas('success');
        $this->assertSame(1, Signature::query()->count());
        $this->assertSame(1, StoredFile::query()->where('purpose', StoredFile::PURPOSE_CMS_SIGNATURE)->count());
        $this->assertSame(1, $this->p7sCount());
        $this->assertSame(1, AuditEvent::query()->where('action', 'contract.signature_completed')->count());
    }

    // --- failure mapping ------------------------------------------------------

    public function test_unsignable_contract_maps_to_safe_croatian_message(): void
    {
        $ctx = $this->registerValidSigner();
        $this->actingAs($ctx['user']);
        $contract = $this->seedContract($ctx['user'], Contract::STATUS_DRAFT, locked: false);

        $response = $this->sign($contract);

        $response->assertRedirect(route('contracts.index'))->assertSessionHas('error');
        $this->assertSame(
            ContractSigningFailurePresenter::message(ContractSigningException::CONTRACT_NOT_SIGNABLE),
            session('error')
        );
        $this->assertSame(0, Signature::query()->count());
    }

    public function test_missing_public_verification_maps_to_safe_message(): void
    {
        $ctx = $this->registerValidSigner();
        $this->actingAs($ctx['user']);
        $contract = $this->seedContract($ctx['user']);
        $this->attachFinalPdf($contract, $ctx['user'], $this->pdfBytes('no-verify'));

        $this->sign($contract)->assertSessionHas('error');

        $this->assertSame(
            ContractSigningFailurePresenter::message(ContractSigningException::PUBLIC_VERIFICATION_NOT_READY),
            session('error')
        );
        $this->assertSame(0, Signature::query()->count());
    }

    public function test_revoked_public_verification_fails_closed_over_http(): void
    {
        $f = $this->signableFixture();
        $f['contract']->public_verification_revoked_at = now();
        $f['contract']->save();

        $this->sign($f['contract'])->assertSessionHas('error');
        $this->assertSame(0, Signature::query()->count());
        $this->assertSame(0, $this->p7sCount());
    }

    public function test_error_message_never_contains_technical_details(): void
    {
        $ctx = $this->registerValidSigner();
        $this->actingAs($ctx['user']);
        $contract = $this->seedContract($ctx['user']);
        // No final PDF at all -> FINAL_PDF_MISSING.
        $this->sign($contract)->assertSessionHas('error');

        $message = (string) session('error');
        foreach (['SQLSTATE', 'Exception', 'openssl', '.p7s', 'storage/', 'contracts/', $this->tempDir] as $fragment) {
            $this->assertStringNotContainsString($fragment, $message);
        }
    }

    public function test_signing_route_is_throttled(): void
    {
        $ctx = $this->registerValidSigner();
        $this->actingAs($ctx['user']);
        // Fails fast (not signable) so six attempts are cheap.
        $contract = $this->seedContract($ctx['user'], Contract::STATUS_DRAFT, locked: false);

        for ($i = 0; $i < 6; $i++) {
            $this->sign($contract)->assertRedirect();
        }

        $this->sign($contract)->assertStatus(429);
    }

    // --- UI surface ------------------------------------------------------------

    public function test_index_shows_ready_state_with_csrf_confirmation_and_loading_behaviour(): void
    {
        $f = $this->signableFixture();

        $html = $this->get(route('contracts.index'))->assertOk()->getContent();

        $this->assertStringContainsString('Spremno za digitalno potpisivanje', $html);
        $this->assertStringContainsString('Potpiši dokument', $html);
        $this->assertStringContainsString(route('contracts.sign.store', $f['contract']), $html);
        $this->assertStringContainsString('name="_token"', $html);
        $this->assertStringContainsString('confirm(', $html);
        $this->assertStringContainsString('disabled = true', $html);
        $this->assertStringContainsString('ne o PAdES/eIDAS/kvalificiranom potpisu', $html);
    }

    public function test_index_shows_not_ready_state_before_public_verification(): void
    {
        $ctx = $this->registerValidSigner();
        $this->actingAs($ctx['user']);
        $contract = $this->seedContract($ctx['user']);
        $this->attachFinalPdf($contract, $ctx['user'], $this->pdfBytes('not-ready'));

        $html = $this->get(route('contracts.index'))->assertOk()->getContent();

        $this->assertStringContainsString('Dokument još nije spreman za potpisivanje', $html);
        $this->assertStringNotContainsString('Potpiši dokument', $html);
    }

    public function test_index_shows_signed_summary_with_download_and_no_secrets(): void
    {
        $f = $this->signableFixture();
        $this->sign($f['contract'])->assertSessionHas('success');

        $html = $this->get(route('contracts.index'))->assertOk()->getContent();

        $this->assertStringContainsString('Digitalni potpis dovršen', $html);
        $this->assertStringContainsString('Preuzmi potpis (.p7s)', $html);
        $this->assertStringContainsString(route('contracts.signature.download', $f['contract']), $html);
        // The signed card hides regeneration and shows no sensitive material.
        $this->assertStringNotContainsString('Generiraj finalni PDF', $html);
        $this->assertStringNotContainsString('Potpiši dokument', $html);
        $cmsPath = (string) StoredFile::query()->where('purpose', StoredFile::PURPOSE_CMS_SIGNATURE)->value('storage_path');
        $this->assertStringNotContainsString($cmsPath, $html);
    }

    public function test_signing_section_is_absent_for_foreign_users_surface(): void
    {
        $f = $this->signableFixture();
        $this->actingAs(User::factory()->create());

        $html = $this->get(route('contracts.index'))->assertOk()->getContent();

        // The foreign user's index simply does not list the victim's contract.
        $this->assertStringNotContainsString(route('contracts.sign.store', $f['contract']), $html);
        $this->assertStringNotContainsString('Potpiši dokument', $html);
    }
}
